// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0TTByEFSUQGT_WWlT6noG9z6A5WRqrG4',
    appId: '1:731752537384:android:d13943ae9e66b849fc041d',
    messagingSenderId: '731752537384',
    projectId: 'synto-75017',
    storageBucket: 'synto-75017.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy6jXZRZs0r1iZNZQfzO9q2wmYct5tlqY',
    appId: '1:731752537384:ios:4519f3b3f6156683fc041d',
    messagingSenderId: '731752537384',
    projectId: 'synto-75017',
    storageBucket: 'synto-75017.firebasestorage.app',
    iosBundleId: 'com.synto.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD89HfAdooszo5xMawvUowTkxhYx7rE7aA',
    appId: '1:731752537384:web:b2f69c5595e740cdfc041d',
    messagingSenderId: '731752537384',
    projectId: 'synto-75017',
    authDomain: 'synto-75017.firebaseapp.com',
    storageBucket: 'synto-75017.firebasestorage.app',
    measurementId: 'G-5H3Q3JTZWR',
  );

}